version: '3'
services:
  web:
    build: ~/Imaya/GOS/imageConfig/web_image
    # ports:
    #   - "5000:5000"
    volumes:
      - ~/Imaya/GOS/imageConfig/web_image:/flask_content
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  vault:
    build: ~/Imaya/GOS/imageConfig/vault_image
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_CACERT=./cert.pem
    entrypoint: vault server -config=vault.json
    ports:
      - "8200:8200"
    depends_on:
      - "web"
  honey_pot:
    build: /home/whirldata/Imaya/GOS/imageConfig/honey_pot_image
    cap_add:
      - NET_ADMIN
    # command: ["/usr/sbin/sshd"]
    # entrypoint: 
    #   - mysqld
    depends_on:
      - "web"
      - "vault"
  proxy:
    build: ~/Imaya/GOS/imageConfig/nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
      - vault
      - honey_pot